### ISSUE TITLE
Migrate to Project Pythia

### ISSUE THREAD

**Issue by mgrover1** [tlincheck/lasso-those-clouds-cookbook#15]
@tlincheck - is there interest in migrating to this Project Pythia and making this a formal cookbook?

**Comment by tlincheck** [comment]
Hi @mgrover1. I believe this link is the finished cookbook on Project Pythia (https://tlincheck.github.io/lasso-those-clouds-cookbook/README.html). 

Let me know if and what steps to take to make this a formal cookbook if it is not already so. Thanks!

**Comment by mgrover1** [comment]
@tlincheck thanks for the quick response! The initial step would be transfer the repository under the Project Pythia organization. I will add you as a member of the organization, then you would go under "Settings" and select Transfer Ownership.

**Comment by tlincheck** [comment]
Ownership has been transferred. Is there a way to update the link to the cookbook website on the github page?

**Comment by mgrover1** [comment]
That is now fixed 👍
